name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build and tag image
      run: docker build . --file Dockerfile --tag rbesar/sneakers:1.0
    
    - name: push to dockerhub
      run: docker login -u ${{secrets.HUB_USERNAME}} -p ${{secrets.HUB_SECRET}} && docker push rbesar/sneakers:1.0
